export const campaignNames = [
  'Shannasaves Afghanistan',
  'Piedasaves Albania',
  'Lisandrsaves Algeria',
  'Linsaves Andorra',
  'Sausaves Angola',
  'Sofisaves Antigua & Deps',
  'Lorettsaves Argentina',
  'Sophisaves Armenia',
  'Lersaves Australia',
  'Pennsaves Austria',
  'Evelysaves Azerbaijan',
  'Fannsaves Bahamas',
  'Ricksaves Bahrain',
  'Stacesaves Bangladesh',
  'Suzisaves Barbados',
  'Nelsosaves Belarus',
  'Tifansaves Belgium',
  'Jennsaves Belize',
  'Annettsaves Benin',
  'Sulemsaves Bhutan',
  'Osvaldsaves Bolivia',
  'Marylouissaves Bosnia Herzegovina',
  'Jasaves Botswana',
  'Sharlensaves Brazil',
  'Fondsaves Brunei',
  'Clarettsaves Bulgaria',
  'Jansaves Burkina',
  'Barrsaves Burundi',
  'Ruthannsaves Cambodia',
  'Elwoosaves Cameroon',
  'Audresaves Canada',
  'Tobisaves Cape Verde',
  'Cathisaves Central African Rep',
  'Shebsaves Chad',
  'Porshsaves Chile',
  'Josaves China',
  'Maribetsaves Colombia',
  'Shonnsaves Comoros',
  'Sheltosaves Congo',
  'Lisettsaves Congo {Democratic Rep}',
  'Socorrsaves Costa Rica',
  'Trissaves Croatia',
  'Pesaves Cuba',
  'Tannesaves Cyprus',
  'Laversaves Czech Republic',
  'Alainsaves Denmark',
  'Lorenzsaves Djibouti',
  'Kacesaves Dominica',
  'Dariusaves Dominican Republic',
  'Rsaves East Timor',
  'Luther saves Ecuador',
  'Ariana saves Egypt',
  'Gilberte saves El Salvador',
  'Lyman saves Equatorial Guinea',
  'Piedad saves Eritrea',
  'Easter saves Estonia',
  'Ignacia saves Ethiopia',
  'Harry saves Fiji',
  'Benjamin saves Finland',
  'Samual saves France',
  'Jadwiga saves Gabon',
  'Dan saves Gambia',
  'Julienne saves Georgia',
  'Kayla saves Germany',
  'Ewa saves Ghana',
  'Sabina saves Greece',
  'Darline saves Grenada',
  'Ramiro saves Guatemala',
  'Ernestina saves Guinea',
  'Deandra saves Guinea-Bissau',
  'Lucienne saves Guyana',
  'Corina saves Haiti',
  'Candie saves Honduras',
  'Karoline saves Hungary',
  'Clayton saves Iceland',
  'Valrie saves India',
  'Waneta saves Indonesia',
  'Rosalind saves Iran',
  'Viola saves Iraq',
  'Chanel saves Ireland {Republic}',
  'Melvina saves Israel',
  'Olive saves Italy',
  'Waltraud saves Ivory Coast',
  'Matha saves Jamaica',
  'Gia saves Japan',
  'Raven saves Jordan',
  'Eufemia saves Kazakhstan',
  'Genesis saves Kenya',
  'Neoma saves Kiribati',
  'Sulema saves Korea North',
  'September saves Korea South',
  'Antwan saves Kosovo',
  'Kieth saves Kuwait',
  'Mendy saves Kyrgyzstan',
  'Lorina saves Laos',
  'Jamar saves Latvia',
  'Jeanett saves Lebanon',
  'Dessie saves Lesotho',
  'Jessi saves Liberia',
  'Patrisaves Libya',
  'Zachariah saves Liechtenstein',
  'Norbert saves Lithuania',
  'Kareem saves Luxembourg',
  'Minta saves Macedonia',
  'Brittany saves Madagascar',
  'Idalia saves Malawi',
  'Leandra saves Malaysia',
  'Olympia saves Maldives',
  'Bettie saves Mali',
  'Ai saves Malta',
  'Temika saves Marshall Islands',
  'Nicolas saves Mauritania',
  'Roseann saves Mauritius',
  'Kymberly saves Mexico',
  'Geraldine saves Micronesia',
  'Elayne saves Moldova',
  'Lindsey saves Monaco',
  'Margy saves Mongolia',
  'Shari saves Montenegro',
  'Nidia saves Morocco',
  'Andrew saves Mozambique',
  'Leia saves Myanmar, {Burma}',
  'Vivan saves Namibia',
  'Tuan saves Nauru',
  'Emory saves Nepal',
  'Britt saves Netherlands',
  'Oretha saves New Zealand',
  'Connie saves Nicaragua',
  'Alda saves Niger',
  'Christene saves Nigeria',
  'Kattie saves Norway',
  'Virgina saves Oman',
  'Hayley saves Pakistan',
  'Jannie saves Palau',
  'Iola saves Panama',
  'Marline saves Papua New Guinea',
  'Christeen saves Paraguay',
  'Johna saves Peru',
  'Reynaldo saves Philippines',
  'Dayna saves Poland',
  'Neoma saves Portugal',
  'Judson saves Qatar',
  'Jacquline saves Romania',
  'Trinity saves Russian Federation',
  'Margareta saves Rwanda',
  'Clora saves St Kitts & Nevis',
  'Elli saves St Lucia',
  'Kyla saves Saint Vincent & the Grenadines',
  'Jacqui saves Samoa',
  'Jinny saves San Marino',
  'Lewis saves Sao Tome & Principe',
  'Hannelore saves Saudi Arabia',
  'Dorsey saves Senegal',
  'Mirna saves Serbia',
  'Collin saves Seychelles',
  'Ross saves Sierra Leone',
  'Setsuko saves Singapore',
  'Claudette saves Slovakia',
  'Sebrina saves Slovenia',
  'Divina saves Solomon Islands',
  'Isabella saves Somalia',
  'Agripina saves South Africa',
  'Nga saves South Sudan',
  'Dora saves Spain',
  'Misty saves Sri Lanka',
  'Olivia saves Sudan',
  'Yoshie saves Suriname',
  'Tobi saves Swaziland',
  'Sena saves Sweden',
  'Tamatha saves Switzerland',
  'Stephani saves Syria',
  'Son saves Taiwan',
  'Charolette saves Tajikistan',
  'Candace saves Tanzania',
  'Fumiko saves Thailand',
  'Queenie saves Togo',
  'Anabel saves Tonga',
  'Winnifred saves Trinidad & Tobago',
  'Xiomara saves Tunisia',
  'Tegan saves Turkey',
  'Sharla saves Turkmenistan',
  'Jennie saves Tuvalu',
  'Kraig saves Uganda',
  'Garfield saves Ukraine',
  'Mayola saves United Arab Emirates',
  'Codi saves United Kingdom',
  'Mauro saves United States',
  'Adah saves Uruguay',
  'Velva saves Uzbekistan',
  'Sonya saves Vanuatu',
  'Tory saves Vatican City',
  'Cherryl saves Venezuela',
  'Yun saves Vietnam',
  'Tami saves Yemen',
  'Agueda saves Zambia',
  'Bernardina saves Zimbabwe'
]